// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR8aRXZAd7opNuiAgNA4QnYAgG7rFwpD0',
    appId: '1:453053787314:web:259cc5be4e98737bbc2dab',
    messagingSenderId: '453053787314',
    projectId: 'iitu-campus-form',
    authDomain: 'iitu-campus-form.firebaseapp.com',
    storageBucket: 'iitu-campus-form.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiolyIDp50CNa3YgYCQ398EklLmtjmPCE',
    appId: '1:453053787314:android:80a807fe101b3631bc2dab',
    messagingSenderId: '453053787314',
    projectId: 'iitu-campus-form',
    storageBucket: 'iitu-campus-form.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR8aRXZAd7opNuiAgNA4QnYAgG7rFwpD0',
    appId: '1:453053787314:web:05a01cba2bdc3967bc2dab',
    messagingSenderId: '453053787314',
    projectId: 'iitu-campus-form',
    authDomain: 'iitu-campus-form.firebaseapp.com',
    storageBucket: 'iitu-campus-form.firebasestorage.app',
  );
}
